name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches: 
    - main

permissions:
  contents: read

jobs:
  build-core:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      with:
        persist-credentials: false
    - name: Update pkg-config database
      run: sudo ldconfig
    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2.10.0
    - name: Cache build
      id: cache-build
      uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
      with:
        path: build-cache-st
        key: build-cache-st-v1-${{ hashFiles('Dockerfile', 'Makefile', 'build/*') }}
        restore-keys: |
          build-cache-st-v1-
    - name: Build ffmpeg-core
      run: make prd EXTRA_ARGS="--cache-from=type=local,src=build-cache-st --cache-to=type=local,dest=build-cache-st,mode=max"
    - name: Upload core
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: ffmpeg-core
        path: packages/core/dist/*
  build-core-mt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      with:
        persist-credentials: false
    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2.10.0
    - name: Cache build
      id: cache-build
      uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
      with:
        path: build-cache-mt
        key: build-cache-mt-v1-${{ hashFiles('Dockerfile', 'Makefile', 'build/*') }}
        restore-keys: |
          build-cache-v1-
    - name: Build ffmpet-core-mt
      run: make prd-mt EXTRA_ARGS="--cache-from=type=local,src=build-cache-mt --cache-to=type=local,dest=build-cache-mt,mode=max"
    - name: Upload core-mt
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: ffmpeg-core-mt
        path: packages/core-mt/dist/*
  tests:
    runs-on: ubuntu-latest
    needs:
      - build-core
      - build-core-mt
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      with:
        persist-credentials: false
    - name: Download ffmpeg-core
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: ffmpeg-core
        path: packages/core/dist
    - name: Download ffmpeg-core-mt
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: ffmpeg-core-mt
        path: packages/core-mt/dist
    - name: Use Node.js 18
      uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
      with:
        node-version: 18.x
    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          node-modules-
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
